/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visao;

import controle.GestorC;
import javax.swing.JOptionPane;

/**
 *
 * @author noubH
 */
public class jFrameCadastro extends javax.swing.JFrame {

    private GestorC DadosGestor;
    JFrameLogin jfp = new JFrameLogin();

    /**
     * Creates new form jFrameCadastro
     */
    public jFrameCadastro() {
        initComponents();

        //Centralizar Formulário
        setLocationRelativeTo(null);

        this.DadosGestor = new GestorC();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPCodigo = new javax.swing.JPanel();
        jLNome = new javax.swing.JLabel();
        jLNascimento = new javax.swing.JLabel();
        jLCPF = new javax.swing.JLabel();
        jCSexo = new javax.swing.JComboBox<>();
        jLSexo = new javax.swing.JLabel();
        jTXNome = new javax.swing.JTextField();
        jTXCPF = new javax.swing.JTextField();
        jTXNascimento = new javax.swing.JTextField();
        jPAcesso = new javax.swing.JPanel();
        jTXLogin = new javax.swing.JTextField();
        jLSenha = new javax.swing.JLabel();
        jLLogin = new javax.swing.JLabel();
        jPSenha = new javax.swing.JPasswordField();
        jPContato = new javax.swing.JPanel();
        jTXTelefone = new javax.swing.JTextField();
        jLTelefone = new javax.swing.JLabel();
        jTXEmail = new javax.swing.JTextField();
        jLEmail = new javax.swing.JLabel();
        jBVoltar = new javax.swing.JButton();
        jBCadastrar = new javax.swing.JButton();
        lBTitulo = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Gestor");

        jPCodigo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Pessoais", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPCodigo.setToolTipText("");
        jPCodigo.setName("JPanelDados"); // NOI18N

        jLNome.setText("Nome:");

        jLNascimento.setText("Nascimento:");

        jLCPF.setText("CPF:");

        jCSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecionar", "Masculino", "Feminino" }));
        jCSexo.setMaximumSize(new java.awt.Dimension(150, 35));
        jCSexo.setMinimumSize(new java.awt.Dimension(150, 35));
        jCSexo.setPreferredSize(new java.awt.Dimension(150, 35));

        jLSexo.setText("Sexo:");

        jTXNome.setToolTipText("");
        jTXNome.setMaximumSize(new java.awt.Dimension(150, 35));
        jTXNome.setMinimumSize(new java.awt.Dimension(150, 35));
        jTXNome.setPreferredSize(new java.awt.Dimension(150, 35));
        jTXNome.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jTXNomeComponentAdded(evt);
            }
        });
        jTXNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTXNomeActionPerformed(evt);
            }
        });

        jTXCPF.setMaximumSize(new java.awt.Dimension(150, 35));
        jTXCPF.setMinimumSize(new java.awt.Dimension(150, 35));
        jTXCPF.setPreferredSize(new java.awt.Dimension(150, 35));

        jTXNascimento.setMaximumSize(new java.awt.Dimension(150, 35));
        jTXNascimento.setMinimumSize(new java.awt.Dimension(150, 35));
        jTXNascimento.setPreferredSize(new java.awt.Dimension(150, 35));

        javax.swing.GroupLayout jPCodigoLayout = new javax.swing.GroupLayout(jPCodigo);
        jPCodigo.setLayout(jPCodigoLayout);
        jPCodigoLayout.setHorizontalGroup(
            jPCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCodigoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLNascimento)
                    .addComponent(jLNome)
                    .addComponent(jLCPF))
                .addGap(18, 18, 18)
                .addGroup(jPCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPCodigoLayout.createSequentialGroup()
                        .addComponent(jTXNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLSexo)
                        .addGap(18, 18, 18)
                        .addComponent(jCSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTXNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPCodigoLayout.createSequentialGroup()
                        .addComponent(jTXCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPCodigoLayout.setVerticalGroup(
            jPCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPCodigoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLCPF)
                    .addComponent(jTXCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTXNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNome))
                .addGap(18, 18, 18)
                .addGroup(jPCodigoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLSexo)
                    .addComponent(jTXNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLNascimento))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPAcesso.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados de Acesso", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jTXLogin.setMaximumSize(new java.awt.Dimension(150, 35));
        jTXLogin.setMinimumSize(new java.awt.Dimension(150, 35));
        jTXLogin.setPreferredSize(new java.awt.Dimension(150, 35));

        jLSenha.setText("Senha:");

        jLLogin.setText("Login:");

        jPSenha.setMaximumSize(new java.awt.Dimension(150, 35));
        jPSenha.setMinimumSize(new java.awt.Dimension(150, 35));
        jPSenha.setPreferredSize(new java.awt.Dimension(150, 35));

        javax.swing.GroupLayout jPAcessoLayout = new javax.swing.GroupLayout(jPAcesso);
        jPAcesso.setLayout(jPAcessoLayout);
        jPAcessoLayout.setHorizontalGroup(
            jPAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAcessoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLLogin)
                    .addComponent(jLSenha))
                .addGap(18, 18, 18)
                .addGroup(jPAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTXLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPAcessoLayout.setVerticalGroup(
            jPAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPAcessoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLLogin)
                    .addComponent(jTXLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPAcessoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLSenha)
                    .addComponent(jPSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPContato.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados de Contato", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));

        jTXTelefone.setMaximumSize(new java.awt.Dimension(150, 35));
        jTXTelefone.setMinimumSize(new java.awt.Dimension(150, 35));
        jTXTelefone.setPreferredSize(new java.awt.Dimension(150, 35));

        jLTelefone.setText("Telefone:");

        jTXEmail.setMaximumSize(new java.awt.Dimension(150, 35));
        jTXEmail.setMinimumSize(new java.awt.Dimension(150, 35));
        jTXEmail.setPreferredSize(new java.awt.Dimension(150, 35));
        jTXEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTXEmailActionPerformed(evt);
            }
        });

        jLEmail.setText("Email:");

        javax.swing.GroupLayout jPContatoLayout = new javax.swing.GroupLayout(jPContato);
        jPContato.setLayout(jPContatoLayout);
        jPContatoLayout.setHorizontalGroup(
            jPContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPContatoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPContatoLayout.createSequentialGroup()
                        .addComponent(jLTelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTXTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPContatoLayout.createSequentialGroup()
                        .addComponent(jLEmail)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTXEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPContatoLayout.setVerticalGroup(
            jPContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPContatoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTXTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLTelefone))
                .addGap(18, 18, 18)
                .addGroup(jPContatoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTXEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLEmail))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jBVoltar.setText("Cancelar");
        jBVoltar.setMaximumSize(new java.awt.Dimension(150, 35));
        jBVoltar.setMinimumSize(new java.awt.Dimension(150, 35));
        jBVoltar.setPreferredSize(new java.awt.Dimension(150, 35));
        jBVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVoltarActionPerformed(evt);
            }
        });

        jBCadastrar.setText("Cadastrar");
        jBCadastrar.setMaximumSize(new java.awt.Dimension(150, 35));
        jBCadastrar.setMinimumSize(new java.awt.Dimension(150, 35));
        jBCadastrar.setPreferredSize(new java.awt.Dimension(150, 35));
        jBCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCadastrarActionPerformed(evt);
            }
        });

        lBTitulo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lBTitulo.setText("Cadastro de Gestor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(lBTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPCodigo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lBTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBVoltar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTXNomeComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jTXNomeComponentAdded

    }//GEN-LAST:event_jTXNomeComponentAdded

    private void jTXNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTXNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTXNomeActionPerformed

    private void jTXEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTXEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTXEmailActionPerformed

    private void jBVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVoltarActionPerformed
        JFrameLogin jfp = new JFrameLogin();
        jfp.setVisible(true);

        dispose();
    }//GEN-LAST:event_jBVoltarActionPerformed

    private void jBCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCadastrarActionPerformed

        String erro = "";

        // Verificar Erros
        if (jTXCPF.getText().trim().isEmpty()) {
            erro = erro + "Campo CPF não está preenchido...\n";
        }
        if (jTXNome.getText().trim().isEmpty()) {
            erro = erro + "Campo Nome não está preenchido...\n";
        }
        if (jTXNascimento.getText().isEmpty()) {
            erro = erro + "campo nascimento não está preenchido...";
        }
        if (jCSexo.getSelectedItem().equals("Selecionar")) {
            erro = erro + "Sexo não está selecionado...";
        }
        if (jTXEmail.getText().isEmpty()) {
            erro = erro + "campo Email não está preenchido...";
        }
        if (jTXTelefone.getText().isEmpty()) {
            erro = erro + "campo Telefone não preenchido...";
        }
        if (jTXLogin.getText().isEmpty()) {
            erro = erro + "campo Login não está preenchido...";
        }
        if (jPSenha.getText().isEmpty()) {
            erro = erro + "campo Senha não está preenchido...";
        }

        // Se não tiver erros, prossegue
        if (erro.length() == 0) {

            // Resgatar Valores do Formulário
            String cpf = jTXCPF.getText().trim();
            String nome = jTXNome.getText().trim();
            String nascimento = jTXNascimento.getText().trim();
            Object sexo = jCSexo.getSelectedItem();
            String email = jTXEmail.getText().trim();
            String telefone = jTXTelefone.getText().trim();
            String login = jTXLogin.getText().trim();
            String senha = new String(jPSenha.getPassword());
            
            String sx = "I";
            if(sexo == "Feminino"){
                sx = "F";
            } else if (sexo == "Masculino"){
                sx = "M";
            }

            // Verificando se foi possível inserir os dados em uma determinada posição válida da lista
            if (this.DadosGestor.CPFExistente(cpf) == false) {

                if(this.DadosGestor.LoginExistente(login) == false){
                    
                    this.DadosGestor.setDadosGestor(cpf, nome, nascimento, sx, login, senha, email, telefone);
                    
                    if(this.DadosGestor.setCadastrarGestor() == true){
                        JOptionPane.showMessageDialog(null, "Gerente cadastrado com sucesso, use seu login e senha para acessar o nosso Gerenciador!");
                        jfp.setVisible(true);
                        dispose();
                    } else {
                        JOptionPane.showMessageDialog(null, "Atenção, ocorreu um erro ao salvar informações do gestor, tente novamente!"); 
                    }
                    
                } else {
                   JOptionPane.showMessageDialog(null, "Atenção, o LOGIN informado está duplicado!"); 
                }

            } else {
                JOptionPane.showMessageDialog(null, "Atenção, o CPF informado está duplicado!");
            }

        } else {
            JOptionPane.showMessageDialog(null, erro);
        }
    }//GEN-LAST:event_jBCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFrameCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFrameCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFrameCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFrameCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFrameCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCadastrar;
    private javax.swing.JButton jBVoltar;
    private javax.swing.JComboBox<String> jCSexo;
    private javax.swing.JLabel jLCPF;
    private javax.swing.JLabel jLEmail;
    private javax.swing.JLabel jLLogin;
    private javax.swing.JLabel jLNascimento;
    private javax.swing.JLabel jLNome;
    private javax.swing.JLabel jLSenha;
    private javax.swing.JLabel jLSexo;
    private javax.swing.JLabel jLTelefone;
    private javax.swing.JPanel jPAcesso;
    private javax.swing.JPanel jPCodigo;
    private javax.swing.JPanel jPContato;
    private javax.swing.JPasswordField jPSenha;
    private javax.swing.JTextField jTXCPF;
    private javax.swing.JTextField jTXEmail;
    private javax.swing.JTextField jTXLogin;
    private javax.swing.JTextField jTXNascimento;
    private javax.swing.JTextField jTXNome;
    private javax.swing.JTextField jTXTelefone;
    private java.awt.Label lBTitulo;
    // End of variables declaration//GEN-END:variables
}
